### ISSUE TITLE
Big Oresight bug!

### ISSUE THREAD

**Issue by NebbyOtt** [Loikas/MinecraftPlugins#26]
Hi again! My friend found that if you go through a portal while Oresight is active (You've crouched and the ores are visible), when you come back they are permanently visible, even if you break the block, the shulkers remain, and are visible to all players and without the helmet. So as well as fixing this a way to manually remove these shulkers would be nice xD I tried /kill @e[type=shulker] but it doesn't work

**Comment by Loikas** [comment]
Hmm i'll look into it when im back home
