### ISSUE TITLE
Player finding a custom enchant in an endcity despite the EndCityChance being set to 0

### ISSUE THREAD

**Issue by 0nis** [Loikas/MinecraftPlugins#28]
Like the title says, a player found a custom enchant in an endcity, even though the config option for EndCityChance was set to 0 at the time; the enchant they found was traveler 1. I'm using Expanded Enchants version 1.7 on a 1.19 Paper server. For now I've tried setting the config option to -1, but the enchants still seems pretty rare so I don't have a solid way of testing it. 

(Btw I love your plugin!! The enchants are super fun and the players are loving it! Thanks for putting so much time into developing it :D)

**Comment by Loikas** [comment]
Hmm thats weird, i'll take a look

**Comment by Loikas** [comment]
Yes I've made a mistake in the code

**Comment by Loikas** [comment]
Fixed in 1.7.1
