### ISSUE TITLE
Item duplication glitch in ExpandedEnchants

### ISSUE THREAD

**Issue by 0nis** [Loikas/MinecraftPlugins#29]
Hi, me again! (My players are the best bug-testers I swear)

When mining a container with items in it using autosmelt, the container is duplicated. If the items within the container can be mined with autosmelt (such as: stone bricks, diamonds, iron, etc), the items are duplicated too. 
I'm using version 1.7 on a Paper 1.19 server.

Hope this helps!

Edit: I just noticed the console spits out an error when mining a container with autosmelt; https://pastebin.com/kw4HkCMT

**Comment by Loikas** [comment]
Ah the error helps a lot, i will fix it

**Comment by Loikas** [comment]
Fixed in 1.7.1
