### ISSUE TITLE
Not able to repair any vanilla tool/item

### ISSUE THREAD

**Issue by davidoque77** [Loikas/MinecraftPlugins#30]
Everything seems to be working good with the ExpandedEnchants plugin. However, with the plugin installed no one in the server is able to repair any item/tool with the anvil. I reproduced this issue many times with my friends on my spigot servers and it seems it keeps happening. I already tried to turn on/off the option "AllowNoEnchantRepair: true" but it doesn't have any effect. We are not able to repair any tool or item in the anvil. A solution for it would be appreciate it, thanks!

**Comment by Loikas** [comment]
I'll look into it

**Comment by davidoque77** [comment]
> I'll look into it

Highly appreciate it, thank you!

**Comment by Loikas** [comment]
Fixed in 1.7.1
