### ISSUE TITLE
More settings in the config.

### ISSUE THREAD

**Issue by WinTPo** [Loikas/MinecraftPlugins#33]
Make more settings in the config. For example, to prohibit improving the enchantment in the anvil above a certain level.

Protection IV + Protertion IV = Protection V
Protection V + Protection V =  forbid

Lootiong II + Lootiong II = Lootiong III
Lootiong III + Lootiong III =  forbid

But in order to be able to use Protection VII
My situation: I need Protection 6 to not be able to get from the anvil, but something rare. In my case, it fell out of the cases.

Also, the enchantment is Deflect can’t set the time in the config

**Comment by Loikas** [comment]
Will be adding something like this. Not sure if i can easily add allowing protection 6 to be found but not made

Also, the enchantment is Deflect can’t set the time in the config

Did you update your config?
