### ISSUE TITLE
Incompatible custom enchants in end city

### ISSUE THREAD

**Issue by hXR16F** [Loikas/MinecraftPlugins#34]
I found a helmet with Health Boost from a chest in end city so I simply added more enchants. I was wondering why it doesn't work then I realised it [only works on chestplace](https://github.com/Loikas/MinecraftPlugins/wiki/All-custom-enchantments#health-boost). It would be better if the enchants were compatible in chests.
![Untitled](https://user-images.githubusercontent.com/48186982/232295509-72784845-92b7-45be-9886-9c2233b3858b.png)

**Comment by Loikas** [comment]
Hmm that should indeed be impossible, i think this might be fixed in the upcoming update, but im not sure. Please message me if this occurs again in the next update of the plugin
