### ISSUE TITLE
Bedrock players using geyser cant add custom enchants using anvil

### ISSUE THREAD

**Issue by Saxostevesaxo** [Loikas/MinecraftPlugins#35]
The custom enchants cant be added by bedrock player, the enchants dont show in the list of enchants on an item when held by a bedrock player but they do work if they are on the item. If a java player adds the enchants and gives it to a bedrock player this works but the enchants don't show for a bedrock player so they have no way of knowing what enchants are on the item.

**Comment by Loikas** [comment]
Im not sure if i can/will fix this, this is a java spigot plugin
